name: Train ML Model

on:
  push:
    branches: [ "features_FastAPI" ]
  pull_request:
    branches: [ "master" ]

jobs:

  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: python ./src/models/train_model.py
        
    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: ./src/models/trained_model.joblib
        retention-days: 2

  test-api:
    runs-on: ubuntu-latest
    needs: train-model
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
    
    - name: Download model artifact
      uses: actions/download-artifact@v3
      with:
        name: trained-model
        path: ./src/models/trained_model.joblib
        
    # Étapes suivantes pour déployer/utiliser le modèle téléchargé
    - name: lancement du serveur API
      run: |
        #python3 --version
        #pip show uvicorn
        #cd ./src/api
        #uvicorn api:api --host 0.0.0.0 --port 8000 &
        uvicorn --app-dir=./src/api api:api --host 0.0.0.0 --port 8000 &
        sleep 10
        
    - name: test de l'API
      run: |
        #cd ./src/api
        echo "debug ls"
        ls
        echo "fin debug ls"
        echo "debug 2 ls"
        ls ./src/models/
        echo "fin debug 2 ls"
        pytest ./src/api/test_api_serveur.py
        #pytest ./src/api/test_api_fonction.py